# Generated by Django 5.1.6 on 2025-03-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeEcommerce', '0002_alter_orderitem_options_alter_orderitem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
